name: Build and Deploy to AKS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        echo "Creating Docker Buildx builder..."
        docker buildx create --use || echo "Failed to create Docker Buildx builder"
        echo "Building and pushing Docker image..."
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/basic-flask-app:latest --push . || echo "Failed to build and push Docker image"

    # Step: Set up kubeconfig from secret
    - name: Set up kubeconfig
      run: |
        echo "Setting up kubeconfig..."
        echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        echo "Kubeconfig file set up completed."
        ls -l $(pwd)  # Verify kubeconfig file is created
        cat kubeconfig  # Print kubeconfig file for debugging (remove this in production)

    # List available contexts to verify kubeconfig content
    - name: List available contexts
      run: |
        echo "Listing available kubectl contexts:"
        kubectl config get-contexts --v=8 || echo "Failed to list contexts"

    # Step: Set the correct Kubernetes context
    - name: Set the correct Kubernetes context
      run: |
        echo "Attempting to set Kubernetes context to 'myAKSCluster'..."
        kubectl config use-context myAKSCluster --v=8 || echo "Failed to set context to myAKSCluster"

    # Verify the current context after setting
    - name: Verify kubectl context
      run: |
        echo "Verifying current kubectl context..."
        kubectl config current-context --v=8 || echo "Current context is not set correctly"

    # Deploy to AKS using the deployment and service YAML files
    - name: Deploy to AKS
      run: |
        echo "Applying deployment.yaml..."
        kubectl apply --validate=false -f deployment.yaml --v=8 || echo "Failed to apply deployment.yaml"
        echo "Applying service.yaml..."
        kubectl apply --validate=false -f service.yaml --v=8 || echo "Failed to apply service.yaml"

    # Debug kubectl to check pod status and other Kubernetes resources
    - name: Debug kubectl
      run: |
        echo "Fetching pod status for all namespaces..."
        kubectl get pods --all-namespaces --v=8 || echo "Failed to get pods status"
