name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to use version 3

    - name: Login to Docker Hub
      uses: docker/login-action@v3  # Update to use version 2
      
    - name: Build Docker image
      run: docker build -t yourusername/basic-flask-app:latest .

    - name: Push Docker image
      run: docker push yourusername/basic-flask-app:latest
