name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/basic-flask-app:latest --push .

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Update kubeconfig
      run: aws eks --region us-east-2 update-kubeconfig --name EKSTesting

    - name: Deploy to EKS
      run: |
        if kubectl get deployment my-python-app; then
          kubectl set image deployment/my-python-app my-python-app=${{ secrets.DOCKERHUB_USERNAME }}/basic-flask-app:latest
        else
          kubectl create deployment my-python-app --image=${{ secrets.DOCKERHUB_USERNAME }}/basic-flask-app:latest
          kubectl expose deployment my-python-app --type=LoadBalancer --port=80 --target-port=80
        fi
        kubectl rollout status deployment/my-python-app
