name: Build and Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/basic-flask-app:latest --push .

    # Step: Login to Azure using Service Principal
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step: Configure the Kubernetes cluster context for AKS
    - name: Set up AKS context
      run: |
        az aks get-credentials --resource-group myResourceGroup --name myAKSCluster --overwrite-existing

    # Optional: Print the kubeconfig for debugging
    - name: Print kubeconfig
      run: cat ~/.kube/config

    # Verify kubectl context to ensure AKS is configured correctly
    - name: Verify kubectl context
      run: kubectl config current-context

    # Deploy to AKS using the deployment and service YAML files
    - name: Deploy to AKS
      run: |
        kubectl apply --validate=false -f deployment.yaml
        kubectl apply --validate=false -f service.yaml

    # Debug kubectl to check pod status and other Kubernetes resources
    - name: Debug kubectl
      run: kubectl get pods --all-namespaces --v=8
